spring:
   application:
   datasource:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      password: Passw0rd@1234567
      url: jdbc:sqlserver://optimusdevmi.a59544804564.database.windows.net; databaseName=optimus-sql-dev
      username: optimus
   jpa:
      database-platform: org.hibernate.dialect.SQLServer2012Dialect
      hibernate:
        ddl-auto: none
      show-sql: true
spring:
  application:
    name: CONFIG-SERVER-DEV
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: 'true'
    path: /swagger-ui.html
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
