spring:
  application:
    name: CONFIG-SERVER
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://hjtestsrv.birlasoft.com:8761/eureka/
  instance:
    hostname: hjtestsrv.birlasoft.com
